[package]
name = "parsiphae"
version = "0.1.0"
authors = ["Leon von Mulert <leonvonmulert@gmail.com>"]

[dependencies]
clap = "2.32.0"
encoding = "0.2.33"
glob = "0.2.11"
lazy_static = "1.0.1"
time = "0.1"

[dependencies.nom]
version = "4.0.0"
features = ["verbose-errors"]


